<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<meta charset="utf-8" />';
echo '<meta';
echo 'name="viewport"';
echo 'content="width=device-width, initial-scale=1.0, user-scalable=0"';
echo '/>';
echo '<title>HealthHub</title>';
echo '';
echo '';
echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
echo '';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="assets/plugins/fontawesome/css/fontawesome.min.css"';
echo '/>';
echo '<link rel="stylesheet" href="assets/plugins/fontawesome/css/all.min.css" />';
echo '';
echo '<link rel="stylesheet" href="assets/css/style.css" />';
echo '';
echo '<!--[if lt IE 9]>';
echo '<script src="assets/js/html5shiv.min.js"></script>';
echo '<script src="assets/js/respond.min.js"></script>';
echo '<![endif]-->';
echo '</head>';
echo '<body>';
echo '<div class="main-wrapper">';
echo '<header class="header">';
echo '<nav class="navbar navbar-expand-lg header-nav">';
echo '<div class="navbar-header">';
echo '<a id="mobile_btn" href="javascript:void(0);">';
echo '<span class="bar-icon">';
echo '';
echo '</span>';
echo '</a>';
echo '<a href="index.html" class="navbar-brand logo">';
echo '<img src="assets/img/logo.png" class="img-fluid" alt="Logo" />';
echo '</a>';
echo '</div>';
echo '<div class="main-menu-wrapper">';
echo '<div class="menu-header">';
echo '';
echo '<a id="menu_close" class="menu-close" href="javascript:void(0);">';
echo '<i class="fas fa-times"></i>';
echo '</a>';
echo '</div>';
echo '';
echo '</div>';
echo '<ul class="nav header-navbar-rht">';
echo '<li class="nav-item contact-item">';
echo '<div class="header-contact-img">';
echo '<i class="far fa-hospital"></i>';
echo '</div>';
echo '<div class="header-contact-detail">';
echo '<p class="contact-header">Contact</p>';
echo '<p class="contact-info-header">+250 784 200 694</p>';
echo '</div>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link header-login" href="login.html"';
echo '>login / Signup';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '</header>';
echo '';
echo '<section class="section section-search">';
echo '<div class="container-fluid">';
echo '<div class="banner-wrapper">';
echo '<div class="banner-header text-center">';
echo '<h1>Make your life easier</h1>';
echo '<p>';
echo 'Book your appointment today!';
echo '</p>';
echo '</div>';
echo '';
echo '';
echo '</section>';
echo '';
echo '<section class="section home-tile-section">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-md-9 m-auto">';
echo '<div class="section-header text-center">';
echo '<h2>What are you looking for?</h2>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-4 mb-3">';
echo '<div class="card text-center doctor-book-card">';
echo '';
echo '';
echo '<div class="doctor-book-card-content tile-card-content-1">';
echo '<div>';
echo '';
echo '<a';
echo 'href="search.html"';
echo '';
echo '';
echo '>Book Now</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 mb-3">';
echo '<div class="card text-center doctor-book-card">';
echo '<img';
echo 'src="assets/img/doctors/doctor-07.jpg"';
echo 'alt=""';
echo 'class="img-fluid"';
echo '/>';
echo '<div class="doctor-book-card-content tile-card-content-1">';
echo '<div>';
echo '<h3 class="card-title mb-0">Visit a Hospital</h3>';
echo '<a';
echo 'href="search.html"';
echo 'class="btn book-btn1 px-3 py-2 mt-3"';
echo 'tabindex="0"';
echo '>Book Now</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '<section class="section section-specialities">';
echo '<div class="container-fluid">';
echo '<div class="section-header text-center">';
echo '<h2>Clinic and Specialities</h2>';
echo '<p class="sub-title">';
echo 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do';
echo 'eiusmod tempor incididunt ut labore et dolore magna aliqua.';
echo '</p>';
echo '</div>';
echo '<div class="row justify-content-center">';
echo '<div class="col-md-9">';
echo '<div class="specialities-slider slider">';
echo '<div class="speicality-item text-center">';
echo '<div class="speicality-img">';
echo '<img';
echo 'src="assets/img/specialities/specialities-01.png"';
echo 'class="img-fluid"';
echo 'alt="Speciality"';
echo '/>';
echo '<span><i class="fa fa-circle" aria-hidden="true"></i></span>';
echo '</div>';
echo '<p>Urology</p>';
echo '</div>';
echo '';
echo '<div class="speicality-item text-center">';
echo '<div class="speicality-img">';
echo '<img';
echo 'src="assets/img/specialities/specialities-02.png"';
echo 'class="img-fluid"';
echo 'alt="Speciality"';
echo '/>';
echo '<span><i class="fa fa-circle" aria-hidden="true"></i></span>';
echo '</div>';
echo '<p>Neurology</p>';
echo '</div>';
echo '';
echo '<div class="speicality-item text-center">';
echo '<div class="speicality-img">';
echo '<img';
echo 'src="assets/img/specialities/specialities-03.png"';
echo 'class="img-fluid"';
echo 'alt="Speciality"';
echo '/>';
echo '<span><i class="fa fa-circle" aria-hidden="true"></i></span>';
echo '</div>';
echo '<p>Orthopedic</p>';
echo '</div>';
echo '';
echo '<div class="speicality-item text-center">';
echo '<div class="speicality-img">';
echo '<img';
echo 'src="assets/img/specialities/specialities-04.png"';
echo 'class="img-fluid"';
echo 'alt="Speciality"';
echo '/>';
echo '<span><i class="fa fa-circle" aria-hidden="true"></i></span>';
echo '</div>';
echo '<p>Cardiologist</p>';
echo '</div>';
echo '';
echo '<div class="speicality-item text-center">';
echo '<div class="speicality-img">';
echo '<img';
echo 'src="assets/img/specialities/specialities-05.png"';
echo 'class="img-fluid"';
echo 'alt="Speciality"';
echo '/>';
echo '<span><i class="fa fa-circle" aria-hidden="true"></i></span>';
echo '</div>';
echo '<p>Dentist</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section section-doctor">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="section-header">';
echo '<h2>Book an appointment at a hospital</h2>';
echo '';
echo '</div>';
echo '<div class="about-content">';
echo '<p>';
echo 'HealthHub Bookings syncs your calendars while letting customers self-schedule and pay for appointments.';
echo 'Our user interface auto-customizes for your industry, meaning you feel right at home.';
echo '</p>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-8">';
echo '<div class="doctor-slider slider">';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-01.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Ruby Perrin</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MDS - Periodontology and Oral Implantology, BDS';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<span class="d-inline-block average-rating">(17)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $300 - $1000';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-02.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Darren Elder</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'BDS, MDS - Oral & Maxillofacial Surgery';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(35)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $50 - $300';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-03.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Deborah Angel</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MBBS, MD - General Medicine, DNB - Cardiology';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(27)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $100 - $400';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-04.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Sofia Brient</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MBBS, MS - General Surgery, MCh - Urology';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(4)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $150 - $250';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-05.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Marvin Campbell</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MBBS, MD - Ophthalmology, DNB - Ophthalmology';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(66)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $50 - $700';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-06.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Katharine Berthold</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MS - Orthopaedics, MBBS, M.Ch - Orthopaedics';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(52)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li><i class="fas fa-map-marker-alt"></i> Kigali, RW</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $100 - $500';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-07.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Linda Tobin</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MBBS, MD - General Medicine, DM - Neurology';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(43)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li><i class="fas fa-map-marker-alt"></i> Kigali, RW</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $100 - $1000';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="profile-widget">';
echo '<div class="doc-img">';
echo '<a href="doctor-profile.html">';
echo '<img';
echo 'class="img-fluid"';
echo 'alt="User Image"';
echo 'src="assets/img/doctors/doctor-08.jpg"';
echo '/>';
echo '</a>';
echo '<a href="javascript:void(0)" class="fav-btn">';
echo '<i class="far fa-bookmark"></i>';
echo '</a>';
echo '</div>';
echo '<div class="pro-content">';
echo '<h3 class="title">';
echo '<a href="doctor-profile.html">Paul Richard</a>';
echo '<i class="fas fa-check-circle verified"></i>';
echo '</h3>';
echo '<p class="speciality">';
echo 'MBBS, MD - Dermatology , Venereology & Lepros';
echo '</p>';
echo '<div class="rating">';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star filled"></i>';
echo '<i class="fas fa-star"></i>';
echo '<span class="d-inline-block average-rating">(49)</span>';
echo '</div>';
echo '<ul class="available-info">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt"></i> Kigali, RW';
echo '</li>';
echo '<li>';
echo '<i class="far fa-clock"></i> Available on Fri, 22 Mar';
echo '</li>';
echo '<li>';
echo '<i class="far fa-money-bill-alt"></i> $100 - $400';
echo '<i';
echo 'class="fas fa-info-circle"';
echo 'data-toggle="tooltip"';
echo 'title="Lorem Ipsum"';
echo '></i>';
echo '</li>';
echo '</ul>';
echo '<div class="row row-sm">';
echo '<div class="col-6">';
echo '<a href="doctor-profile.html" class="btn view-btn"';
echo '>View Profile</a';
echo '>';
echo '</div>';
echo '<div class="col-6">';
echo '<a href="booking.html" class="btn book-btn">Book Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section section-features">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-md-5 features-img">';
echo '<img';
echo 'src="assets/img/features/feature.png"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '</div>';
echo '<div class="col-md-7">';
echo '<div class="section-header">';
echo '<h2 class="mt-2">Availabe Features in Our Clinic</h2>';
echo '';
echo '</div>';
echo '<div class="features-slider slider">';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-01.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>Patient Ward</p>';
echo '</div>';
echo '';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-02.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>Test Room</p>';
echo '</div>';
echo '';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-03.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>ICU</p>';
echo '</div>';
echo '';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-04.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>Laboratory</p>';
echo '</div>';
echo '';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-05.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>Operation</p>';
echo '</div>';
echo '';
echo '<div class="feature-item text-center">';
echo '<img';
echo 'src="assets/img/features/feature-06.jpg"';
echo 'class="img-fluid"';
echo 'alt="Feature"';
echo '/>';
echo '<p>Medical</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section section-blogs">';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<footer class="footer">';
echo '<div class="footer-top">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-6">';
echo '<div class="footer-widget footer-about">';
echo '<div class="footer-logo">';
echo '<img src="assets/img/footer-logo.png" alt="logo" />';
echo '</div>';
echo '<div class="footer-about-content">';
echo '<p>';
echo 'Make your life easier with us.';
echo '</p>';
echo '<div class="social-icon">';
echo '<ul>';
echo '<li>';
echo '<a href="#" target="_blank"';
echo '><i class="fab fa-facebook-f"></i>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="#" target="_blank"';
echo '><i class="fab fa-twitter"></i>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="#" target="_blank"';
echo '><i class="fab fa-linkedin-in"></i';
echo '></a>';
echo '</li>';
echo '<li>';
echo '<a href="#" target="_blank"';
echo '><i class="fab fa-instagram"></i';
echo '></a>';
echo '</li>';
echo '<li>';
echo '<a href="#" target="_blank"';
echo '><i class="fab fa-dribbble"></i>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<div class="footer-widget footer-menu">';
echo '<h2 class="footer-title">For Patients</h2>';
echo '<ul>';
echo '<li><a href="search.html">Search for Doctors</a></li>';
echo '<li><a href="login.html">Login</a></li>';
echo '<li><a href="register.html">Register</a></li>';
echo '<li><a href="booking.html">Booking</a></li>';
echo '<li>';
echo '<a href="patient-dashboard.html">Patient Dashboard</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<div class="footer-widget footer-menu">';
echo '<h2 class="footer-title">For Hospitals</h2>';
echo '<ul>';
echo '<li><a href="appointments.html">Appointments</a></li>';
echo '<li><a href="chat.html">Chat</a></li>';
echo '<li><a href="login.html">Login</a></li>';
echo '<li><a href="doctor-register.html">Register</a></li>';
echo '<li>';
echo '<a href="doctor-dashboard.html">Hospital Dashboard</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<div class="footer-widget footer-contact">';
echo '<h2 class="footer-title">Contact Us</h2>';
echo '<div class="footer-contact-info">';
echo '<div class="footer-address">';
echo '<span><i class="fas fa-map-marker-alt"></i></span>';
echo '<p>';
echo 'Bumbogo';
echo 'Kigali Innovation City';
echo 'Next to Azam';
echo 'Kigali, Rwanda';
echo '</p>';
echo '</div>';
echo '<p>';
echo '<i class="fas fa-phone-alt"></i>';
echo '+250 784 200 694';
echo '</p>';
echo '<p class="mb-0">';
echo '<i class="fas fa-envelope"></i>';
echo 'info@healthhub.com';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="footer-bottom">';
echo '<div class="container-fluid">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 col-lg-6">';
echo '<div class="copyright-text">';
echo '<p class="mb-0">';
echo '&copy; 2021 HealthHub. All rights reserved.';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '</div>';
echo '';
echo '<script';
echo 'data-cfasync="false"';
echo 'src="../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"';
echo '></script>';
echo '<script src="assets/js/jquery.min.js"></script>';
echo '';
echo '<script src="assets/js/popper.min.js"></script>';
echo '<script src="assets/js/bootstrap.min.js"></script>';
echo '';
echo '<script src="assets/js/slick.js"></script>';
echo '';
echo '<script src="assets/js/script.js"></script>';
echo '</body>';
echo '';
echo '';
echo '</html>';
echo '';
?>